// #include </usr/share/idl/libreoffice/com/sun/star/uno/XInterface.idl>
// #include </usr/local/share/libreoffice/idl/com/sun/star/uno/XInterface.idl>
// /Volumes/Z77ExtremeHDD/Users/dhocker/Source/LibreOffice5.0_SDK/idl/com/sun/star/uno

module com { module smf { module ticker { module getinfo {

    interface XSmf
    {
      // Modeled as an 'any' to allow it to be NULL/None/Missing.
      any getYahoo( [in] string a, [in] any b );
      any getMorningKey( [in] string a, [in] any b );
      any getMorningFin( [in] string a, [in] any b );
      any getMorningQFin( [in] string a, [in] any b );
      // ticker, date, data name (e.g. close)
      any getYahooHist( [in] string a, [in] string b, [in] string c );
      // ticker, date
      any getHistoricalQuote( [in] string a, [in] string b );
    };

}; }; }; };
